In [1]:
import os
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import kstest, uniform

In [2]:
DATASETS = ['kin8nm', 'house_8L', 'puma8NH', 'BNG_stock', 'bank8FM']
METHODS = ['TabPFN', 'GP']
N_REP = 20

RAW_DIR = os.environ.get('TABPFN_UQ_RAW_DIR', 'output_realdata/raw')

# Load all results
results = {}  # results[dataset][seed] = output dict
missing = []
for ds in DATASETS:
    results[ds] = {}
    for seed in range(1, N_REP + 1):
        path = os.path.join(RAW_DIR, f'{ds}_seed{seed}.pickle')
        if not os.path.exists(path):
            missing.append(path)
            continue
        with open(path, 'rb') as f:
            results[ds][seed] = pickle.load(f)

print('Loaded reps per dataset:')
for ds in DATASETS:
    print(f'  {ds}: {len(results[ds])} / {N_REP}')
if missing:
    raise FileNotFoundError(f'Missing {len(missing)} result files; first: {missing[0]}')

Loaded reps per dataset:
  kin8nm: 20 / 20
  house_8L: 20 / 20
  puma8NH: 20 / 20
  BNG_stock: 20 / 20
  bank8FM: 20 / 20

## 1. Calibration Plot (Reliability Diagram)
For each dataset, first average empirical coverage over its 20 repetitions. Then report the mean and sample standard deviation across the five dataset-level means, so the uncertainty bars use datasets as the independent units.

In [3]:
# Average over repetitions within each dataset before aggregating datasets.
dataset_coverage = {m: [] for m in METHODS}

for ds in DATASETS:
    reps = list(results[ds].values())
    for m in METHODS:
        dataset_coverage[m].append(
            np.mean([res[f'{m}_coverage'] for res in reps], axis=0)
        )

pi_levels = next(iter(results[DATASETS[0]].values()))['pi_levels']

fig, ax = plt.subplots(figsize=(5, 5))
colors = {'TabPFN': '#1f77b4', 'GP': '#ff7f0e'}
markers = {'TabPFN': 'o', 'GP': 's'}

ax.plot([0, 1], [0, 1], 'k--', lw=1, label='Perfect calibration')

for m in METHODS:
    cov_arr = np.stack(dataset_coverage[m])  # (n_datasets, n_pi_levels)
    mean_cov = cov_arr.mean(axis=0)
    sd_cov = cov_arr.std(axis=0, ddof=1)
    ax.errorbar(pi_levels, mean_cov, yerr=sd_cov,
                label=m, color=colors[m], marker=markers[m],
                capsize=3, lw=1.5)

ax.set_xlabel('Nominal coverage level', fontsize=12)
ax.set_ylabel('Empirical coverage', fontsize=12)
ax.set_title('Calibration plot (real data)', fontsize=13)
ax.legend()
ax.set_xlim(0.45, 1.0)
ax.set_ylim(0.45, 1.0)
ax.set_aspect('equal')
plt.tight_layout()
plt.savefig('output_realdata/calibration_plot.pdf', bbox_inches='tight')
plt.show()

/var/folders/jp/n0wjhx4j3v92_82rpzg2v00m0000gp/T/ipykernel_15160/86695514.py:36: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 2. PIT Histogram
Within each dataset, pool PIT values over its 20 repetitions and normalize the histogram. The displayed density is the equal-weight mean of the five dataset-level histograms. PIT uses linear interpolation over the 0.025--0.975 predicted-quantile grid and is clipped to 0 or 1 outside that range.

In [4]:
bins = np.linspace(0, 1, 21)
bin_centers = (bins[:-1] + bins[1:]) / 2
dataset_pit_density = {m: [] for m in METHODS}

for ds in DATASETS:
    reps = list(results[ds].values())
    for m in METHODS:
        pit_vals = np.concatenate([res[f'{m}_pit'] for res in reps])
        density, _ = np.histogram(pit_vals, bins=bins, density=True)
        dataset_pit_density[m].append(density)

fig, axes = plt.subplots(1, 2, figsize=(9, 4), sharey=True)

for ax, m in zip(axes, METHODS):
    mean_density = np.mean(dataset_pit_density[m], axis=0)
    ax.bar(bin_centers, mean_density, width=np.diff(bins),
           color=colors[m], alpha=0.7, edgecolor='white', align='center')
    ax.axhline(1.0, color='k', lw=1, ls='--', label='Uniform')
    ax.set_xlabel('PIT value', fontsize=11)
    ax.set_title(m, fontsize=12)

axes[0].set_ylabel('Density', fontsize=11)
axes[0].legend()
fig.suptitle('PIT histograms (equal-weight average across datasets)', fontsize=12)
plt.tight_layout()
plt.savefig('output_realdata/pit_histogram.pdf', bbox_inches='tight')
plt.show()

/var/folders/jp/n0wjhx4j3v92_82rpzg2v00m0000gp/T/ipykernel_15160/1756261125.py:27: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 3. Summary Table
Per-dataset metrics: Coverage@95%, mean interval width at 95%, CRPS, KS-PIT statistic.

In [5]:
rows = []
pi_idx_95 = pi_levels.index(0.95)

for ds in DATASETS:
    reps = results[ds]
    if not reps:
        continue
    for m in METHODS:
        cov95 = np.mean([r[f'{m}_coverage'][pi_idx_95] for r in reps.values()])
        width = np.mean([r[f'{m}_width_95'] for r in reps.values()])
        crps = np.mean([r[f'{m}_crps'] for r in reps.values()])
        pit_vals = np.concatenate([r[f'{m}_pit'] for r in reps.values()])
        ks_stat, _ = kstest(pit_vals, uniform(0, 1).cdf)
        rows.append({
            'Dataset': ds,
            'Method': m,
            'Coverage@95%': float(cov95),
            'Width@95%': float(width),
            'CRPS': float(crps),
            'KS-PIT': float(ks_stat),
        })

df_summary = pd.DataFrame(rows)
display(df_summary.pivot_table(
    index='Dataset', columns='Method',
    values=['Coverage@95%', 'Width@95%', 'CRPS', 'KS-PIT']
).round(3))

# Equal-weight average of the five dataset-level summaries.
df_average = (df_summary.groupby('Method')
              [['Coverage@95%', 'Width@95%', 'CRPS', 'KS-PIT']]
              .mean())
print('\nAveraged across dataset-level means:')
display(df_average.round(3))
os.makedirs('output_realdata', exist_ok=True)
df_summary.to_csv('output_realdata/summary_by_dataset.csv', index=False, float_format='%.3f')
df_average.to_csv('output_realdata/summary_average.csv', float_format='%.3f')

            CRPS        Coverage@95%        KS-PIT        Width@95%
Method        GP TabPFN           GP TabPFN     GP TabPFN        GP TabPFN
Dataset
BNG_stock  0.291  0.244        0.942  0.940  0.031  0.031     1.981  1.653
bank8FM    0.113  0.094        0.936  0.960  0.040  0.021     0.773  0.648
house_8L   0.295  0.213        0.929  0.954  0.119  0.034     2.035  1.654
kin8nm     0.208  0.207        0.943  0.968  0.032  0.030     1.439  1.618
puma8NH    0.376  0.304        0.939  0.939  0.038  0.035     2.529  1.993

Averaged across dataset-level means:

        Coverage@95%  Width@95%   CRPS  KS-PIT
Method
GP             0.938      1.751  0.257   0.052
TabPFN         0.952      1.513  0.212   0.031

In [6]:
# LaTeX table for the paper
print(df_summary.to_latex(index=False, float_format='%.3f'))

\begin{tabular}{llrrrr}
\toprule
Dataset & Method & Coverage@95% & Width@95% & CRPS & KS-PIT \\
\midrule
kin8nm & TabPFN & 0.968 & 1.618 & 0.207 & 0.030 \\
kin8nm & GP & 0.943 & 1.439 & 0.208 & 0.032 \\
house_8L & TabPFN & 0.954 & 1.654 & 0.213 & 0.034 \\
house_8L & GP & 0.929 & 2.035 & 0.295 & 0.119 \\
puma8NH & TabPFN & 0.939 & 1.993 & 0.304 & 0.035 \\
puma8NH & GP & 0.939 & 2.529 & 0.376 & 0.038 \\
BNG_stock & TabPFN & 0.940 & 1.653 & 0.244 & 0.031 \\
BNG_stock & GP & 0.942 & 1.981 & 0.291 & 0.031 \\
bank8FM & TabPFN & 0.960 & 0.648 & 0.094 & 0.021 \\
bank8FM & GP & 0.936 & 0.773 & 0.113 & 0.040 \\
\bottomrule
\end{tabular}